### PR TITLE
homework0

### PR DESCRIPTION
**Pull request by vpascaln**

### CODE REVIEW

**Comment by vpascaln** [comment]
@vannisapascalnelson @rivlev @andreas-weise

**Comment by andreas-weise** [comment]
7/10

Incorrect file name, causing compile command to fail. (-2 points)
Do not merge or close the pull request. (-1 point)

**Comment by vpascaln** [comment]
Good Evening, 
             I do not even understand what merging or closing a pull request. Can you please explain it to me ? 

Vannisa Pascal-Nelson

**Comment by andreas-weise** [comment]
Hi Vannisa,

please see this website for an introduction to the concepts of Git and Github: https://guides.github.com/activities/hello-world/

A merged or closed pull request no longer shows up in the lists that Professor Levitan and I look through to find your submissions. For our purposes it basically just means that it is done, taken care of, no longer relevant. So please only close pull requests if you made a mistake and want to create a new one for us to grade. Leave the pull request that constitutes your submission open so we can easily find it.

Similarly, if you forgot to mention us with the "@" (you did mention us, that part was ok), the request also would not show up. So please always mention us.

Hope this helps.
Andreas

**Pull request merged**
